config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @requests = Request.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/index.html.haml
.o-grid
  .o-grid__cell
    = image_tag 'jesse.jpg'
  .o-grid__cell
    %h1 Hi, I'm Jesse, the office manager.
    = link_to "Requests", requests_path, class: "c-button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jesse</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/@blaze/css@x.x.x/dist/blaze.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="o-grid">
  <div class="o-grid__cell">
    <%= image_tag 'jesse.jpg' %>
  </div>
  <div class="o-grid__cell">
    <h1>Hi, I'm Jesse.</h1>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/requests/index.haml
%h2 Requests

- @requests.each do |request|
  = request.title